-- AlterTable
ALTER TABLE `module` MODIFY `id` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID()));

-- AlterTable
ALTER TABLE `modulepermission` MODIFY `id` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID()));

-- AlterTable
ALTER TABLE `roles` MODIFY `id` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID()));

-- AlterTable
ALTER TABLE `schools` MODIFY `id` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID()));

-- AlterTable
ALTER TABLE `siblings` MODIFY `id` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID()));

-- AlterTable
ALTER TABLE `students` MODIFY `id` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID()));

-- AlterTable
ALTER TABLE `users` MODIFY `id` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID()));
