export const ERROR_MESSAGES = {
    INVALID_REQUEST: 'The request is invalid.',
    NOT_FOUND: 'Resource not found',
    UNAUTHORIZED: 'Access denied',
    NON_STUDENT_UNAUTHORIZED: 'Access denied only student can access this api',
    SERVER_ERROR: 'An unexpected error occurred',
    INVALID_NAME: 'Name is required',
    INVALID_ID: 'Invalid or missing category ID',
    INVALID_HEADER: 'Invalid Authorization in the header',
    INVALID_TOKEN: 'Invalid API Token'
};


export const SUCCESS_MESSAGES = {
    FILE_SAVED: "File successfully saved",
    FILE_DELETED: "File successfully deleted",
    IMAGE_SAVED: "Image Saved Successfully",
    USER_DELETED: "User Successfully deleted",
    SCHOOL_DELETED: "School Successfully deleted",
    ACADEMIC_YEAR_DELETED: "Academic year Successfully deleted",
    SPONSORSHIP_DELETED: "Sponsorship Successfully deleted",
    ANNOUNCEMENT_DELETED: "Announcement Successfully deleted"
}

export enum APPLICATION_STAGE {
    POOLING = "POOLING", 
    APPLICATION_LIST = "APPLICATION_LIST",
    RANKING_SELECTION = "RANKING_SELECTION",
    FINAS_PROPER = "FINAS_PROPER"
}

export enum APPLICATION_STATUS {
    // Pooling Stage Statuses
    PENDING_POOLING = "PENDING_POOLING",
    FOLLOW_UP = "FOLLOW_UP",
    COMPLETE = "COMPLETE",
    REJECTED = "REJECTED", // Common, used in multiple stages

    // Application List Stage Statuses
    PENDING_APPLICATION_LIST = "PENDING_APPLICATION_LIST",
    APPROVED = "APPROVED",

    // Ranking Selection Stage Statuses
    PENDING_RANKING_SELECTION = "PENDING_RANKING_SELECTION",
    RANKED = "RANKED",
    NOT_QUALIFIED = "NOT_QUALIFIED",

    // Final Selection Stage Statuses
    AWARDED = "AWARDED",
}

export enum EvaluationStatus {
    PENDING = "PENDING",
    PASSED = "PASSED",
    FAILED = "FAILED",
}

export enum TableEnum {
    STUDENT = 'student',
    SPONSORSHIP_APPLICATION = 'sponsorshipApplications',
}

export enum ColumnEnum {
    // Academic
    GWA = 'gwa',
    COLLEGE_YEAR_LEVEL = 'college_year_level',
    G12_YEAR_OF_GRADUATION = 'g12_year_of_graduation',

    // Family & Income
    FATHER_INCOME = 'father_income',
    MOTHER_INCOME = 'mother_income',
    GUARDIAN_INCOME = 'guardian_income',
    NUMBER_OF_SIBLINGS = 'number_of_siblings',

    // Physical/Identity
    IS_SOLO_PARENT = 'is_solo_parent',
    IS_CHILD_OF_SOLO_PARENT = 'is_child_of_solo_parent',
    IS_INDIGENOUS_PEOPLE = 'is_indigenous_people',
    IS_SPED = 'is_sped',
    IS_PWD = 'is_pwd',

    // Sponsorship Application Specific
    INTERVIEW_STATUS = 'interview_status',
    EXAM_STATUS = 'exam_status',

    // gender specific
    SEX = 'sex'
}

export const TableColumnMap: Record<TableEnum, ColumnEnum[]> = {
    [TableEnum.STUDENT]: [
        // Academic
        ColumnEnum.GWA,
        ColumnEnum.COLLEGE_YEAR_LEVEL,
        ColumnEnum.G12_YEAR_OF_GRADUATION,

        // Family & Income
        ColumnEnum.FATHER_INCOME,
        ColumnEnum.MOTHER_INCOME,
        ColumnEnum.GUARDIAN_INCOME,
        ColumnEnum.NUMBER_OF_SIBLINGS,

        // Physical/Identity
        ColumnEnum.IS_SOLO_PARENT,
        ColumnEnum.IS_CHILD_OF_SOLO_PARENT,
        ColumnEnum.IS_INDIGENOUS_PEOPLE,
        ColumnEnum.IS_SPED,
        ColumnEnum.IS_PWD,
    ],
    [TableEnum.SPONSORSHIP_APPLICATION]: [
        ColumnEnum.INTERVIEW_STATUS,
        ColumnEnum.EXAM_STATUS,
    ],
};

export const VALIDATION_MESSAGES = {
    FIRST_NAME_REQUIRED: 'First name is required and should be a string',
    LAST_NAME_REQUIRED: 'Last name is required and should be a string',
    EMAIL_INVALID: 'Invalid email address',
    USERNAME_INVALID: 'Invalid Username',
    MOBILE_NUMBER_INVALID: 'Invalid mobile number',
    SEX_INVALID: 'Sex must be Male, Female, or Other',
    BIRTHDATE_INVALID: 'Birthdate must be a valid date',
    HEIGHT_INVALID: 'Height must be a positive number',
    WEIGHT_INVALID: 'Weight must be a positive number',
    PERMANENT_ADDRESS_REQUIRED: 'Permanent street is required',
    PERMANENT_BRG_ID_INVALID: 'Permanent barangay ID must be an integer',
    PERMANENT_BRG_ID_NOT_FOUND: 'Permanent barangay ID not found in the system',
    PERMANENT_CITYMUN_ID_INVALID: 'Permanent city municipality ID must be an integer',
    PERMANENT_CITYMUN_ID_NOT_FOUND: 'Permanent city municipality ID not found in the system',
    PERMANENT_PROVINCE_ID_INVALID: 'Permanent province ID must be an integer',
    PERMANENT_PROVINCE_ID_NOT_FOUND: 'Permanent province ID not found in the system',
    PERMANENT_REGION_ID_INVALID: 'Permanent region ID must be an integer',
    PERMANENT_REGION_ID_NOT_FOUND: 'Permanent region ID not found in the system',
    CURRENT_ADDRESS_REQUIRED: 'Current street is required',
    CURRENT_BRG_ID_INVALID: 'Current barangay ID must be an integer',
    CURRENT_BRG_ID_NOT_FOUND: 'Current barangay ID not found in the system',
    CURRENT_CITYMUN_ID_INVALID: 'Current city municipality ID must be an integer',
    CURRENT_CITYMUN_ID_NOT_FOUND: 'Current city municipality ID not found in the system',
    CURRENT_PROVINCE_ID_INVALID: 'Current province ID must be an integer',
    CURRENT_PROVINCE_ID_NOT_FOUND: 'Current province ID not found in the system',
    CURRENT_REGION_ID_INVALID: 'Current region ID must be an integer',
    CURRENT_REGION_ID_NOT_FOUND: 'Current region ID not found in the system',
    EMERGENCY_CONTACT_NAME_REQUIRED: 'Emergency contact name is required',
    EMERGENCY_CONTACT_NUMBER_INVALID: 'Emergency contact number must be a valid phone number',
    G12_ACADEMIC_STRAND_REQUIRED: 'G12 academic strand is required',
    G12_PROGRAM_NAME_REQUIRED: 'G12 program name is required',
    G12_YEAR_OF_GRADUATION_INVALID: 'G12 year of graduation must be a valid year',
    G12_SCHOOL_ID_INVALID: 'G12 school ID must be an integer',
    G12_SCHOOL_ID_NOT_FOUND: 'G12 school ID not found in the system',
    COLLEGE_PROGRAM_NAME_REQUIRED: 'College program name is required',
    COLLEGE_YEAR_LEVEL_INVALID: 'College year level must be an integer',
    COLLEGE_SCHOOL_ID_INVALID: 'College school ID must be an integer',
    COLLEGE_SCHOOL_ID_NOT_FOUND: 'College school ID not found in the system',
    FATHER_FIRST_NAME_REQUIRED: 'Father\'s first name is required',
    FATHER_LAST_NAME_REQUIRED: 'Father\'s last name is required',
    FATHER_OCCUPATION_REQUIRED: 'Father\'s occupation is required',
    FATHER_MOBILE_NUMBER_INVALID: 'Father\'s mobile number must be valid',
    MOTHER_FIRST_NAME_REQUIRED: 'Mother\'s first name is required',
    MOTHER_LAST_NAME_REQUIRED: 'Mother\'s last name is required',
    MOTHER_OCCUPATION_REQUIRED: 'Mother\'s occupation is required',
    MOTHER_MOBILE_NUMBER_INVALID: 'Mother\'s mobile number must be valid',
    GUARDIAN_FIRST_NAME_REQUIRED: 'Guardian\'s first name is required',
    GUARDIAN_LAST_NAME_REQUIRED: 'Guardian\'s last name is required',
    GUARDIAN_OCCUPATION_REQUIRED: 'Guardian\'s occupation is required',
    GUARDIAN_MOBILE_NUMBER_INVALID: 'Guardian\'s mobile number must be valid',
    SIBLINGS_REQUIRED: 'Siblings must be an array of sibling objects',
    SIBLING_NAME_REQUIRED: 'Sibling name is required',
    SIBLING_BIRTHDATE_INVALID: 'Sibling birthdate must be a valid date',
    SIBLING_AGE_INVALID: 'Sibling age must be a positive integer',
    SIBLING_STATUS_REQUIRED: 'Sibling status is required',
    SIBLING_LIVING_WITH_PARENTS_INVALID: 'Sibling livingWithParents must be a boolean',
    SIBLING_OWN_HOUSE_INVALID: 'Sibling ownHouse must be a boolean',
    PASSWORD_EMPTY: "Invalid Password",
    EMAIL_IN_USE: "Email Already Used",
    USERNAME_IN_USE: "Username Already Used",
    PASSWORD_REQUIRED: "Password Required",
    PASSWORD_LENGTH: "Password Minimum length is 6",
    PASSWORD_MISMATCH: "Password Mismatch",
    INVALID_ROLE: "Invalid Role",
    INVALID_MOBILE_NUMBER: "Invalid Phone Number",
    INVALID_FILE_TYPE: "File must be pdf or docs",
    INVALID_IMG_TYPE: "File must be png, jpeg or jpg",
    MISSING_FILE_TYPE_ID: "File type ID is required",
    INVALID_FILE_TYPE_ID: "File type ID is Invalid",
    INVALID_REGION: "Region code must be a string",
    MISSING_REGION: "Region code is required",
    NOT_FOUND_REGION: "Region does not exist in the system",
    INVALID_PROVINCE: "Province code must be a string",
    MISSING_PROVINCE: "Province code is required",
    NOT_FOUND_PROVINCE: "Province does not exist in the system",
    INVALID_CITYMUN: "City/Municipality code must be a string",
    MISSING_CITYMUN: "City/Municipality code is required",
    NOT_FOUND_CITYMUN: "City/Municipality does not exist in the system",
    FILE_ID_REQUIRED: "File Id is Required",
    FILE_ID_NOT_FOUND: "File not found",
    STUDENT_ID_REQUIRED: "Student Id is Required",
    STUDENT_NOT_FOUND: "Student not found",
    USER_ID_REQUIRED: "userId is required",
    STUDENT_ALREADY_APPLIED: "Student already applied",
    USER_NOT_FOUND: " User not found",
    USER_NO_STUDENT_INFO: "User don't have student information",
    SCHOOL_ID_REQUIRED: "School Id is Required",
    SCHOOL_ID_NOT_FOUND: "School Id is not found in the system",
    BRG_ID_INVALID: 'Permanent barangay ID must be an integer',
    BRG_ID_NOT_FOUND: 'Permanent barangay ID not found in the system',
    CITYMUN_ID_INVALID: 'Permanent city municipality ID must be an integer',
    CITYMUN_ID_NOT_FOUND: 'Permanent city municipality ID not found in the system',
    PROVINCE_ID_INVALID: 'Permanent province ID must be an integer',
    PROVINCE_ID_NOT_FOUND: 'Permanent province ID not found in the system',
    SCHOOL_NAME_INVALID: 'School name invalid',
    SCHOOL_NAME_ALREADY_EXIST: 'School name already exist',
    SCHOOL_TYPE_INVALID: 'schoolType must be either "private" or "public"',
    ACADEMIC_YEAR_START_REQUIRED: "academicYearStart is required",
    ACADEMIC_YEAR_END_REQUIRED: "academicYearEnd is required",
    ACADEMIC_YEAR_TERM_REQUIRED: "schoolTerm is required",
    ACADEMIC_YEAR_DATE_FROM_REQUIRED: "dateFrom is required",
    ACADEMIC_YEAR_DATE_TO_REQUIRED: "dateTo is required",
    ACADEMIC_YEAR_ALREADY_EXISTS: "Academic year already exists",
    ACADEMIC_YEAR_ID_REQUIRED: "AcademicYearId is required",
    ACADEMIC_YEAR_ID_NOT_FOUND: "AcademicYearId not found",
    SPONSORSHIP_ID_REQUIRED: "sponsorshipId is required",
    SPONSORSHIP_ID_NOT_FOUND: "sponsorshipId not found",
    SPONSORSHIP_NAME_REQUIRED: "name is required for sponsorship",
    SPONSORSHIP_NAME_INVALID: "Sponsorship with the same name and batch number already exist",
    SPONSORSHIP_DURATION_FROM_REQUIRED: "durationFrom is required and must be date",
    SPONSORSHIP_DURATION_TO_REQUIRED: "durationTo is required and must be date",
    SPONSORSHIP_DURATION_INVALID: "durationTo is less than durationFrom",
    SPONSORSHIP_BATCH_NUMBER_REQUIRED: "batchNumber is required",
    SPONSORSHIP_LIMIT_REQUIRED: "limit is required or must be greater then zero",
    SPONSORSHIP_SLOT_REQUIRED: "slot is required or must be greater then zero",
    SPONSORSHIP_FUND_ALLOCATION_REQUIRED: "fundAllocation is required",
    SPONSORSHIP_SPONSOR_ID_REQUIRED: "sponsorId is required for sponsorship",
    SPONSORSHIP_SPONSOR_ID_INVALID: "sponsorId is invalid or the user is not a sponsor",
    SPONSORSHIP_ACADEMIC_YEAR_ID_REQUIRED: "academicYearId is required for sponsorship",
    SPONSORSHIP_ACADEMIC_YEAR_ID_INVALID: "academicYearId is invalid",
    SPONSORSHIP_SCHOOL_REQUIRED: "sponsorshipSchool is required",
    SPONSORSHIP_SCHOOL_INVALID: "One of the school id given is invalid or does not exist in the system",
    SPONSORSHIP_REQUIREMENTS_REQUIRED: "sponsorshipRequirements is required",
    SPONSORSHIP_REQUIREMENTS_INVALID: "One of the file id in the requirements is invalid or does not exist in the system",
    SPONSORSHIP_FUND_ALLOCATION_INVALID: "fundAllocation must be greater than 0",
    SPONSORSHIP_FILTER_STATUS_INVALID: "status must be 'active' or 'full'",
    SPONSORSHIP_FILTER_ACADEMIC_YEAR_ID_INVALID: "academic_year_id must be a valid UUID",
    SPONSORSHIP_FILTER_SPONSOR_ID_INVALID: "sponsor_id must be a valid UUID",
    SPONSORSHIP_FILTER_DURATION_FROM_INVALID: "duration_from must be a valid ISO 8601 date",
    SPONSORSHIP_FILTER_DURATION_TO_INVALID: "duration_to must be a valid ISO 8601 date",
    REMARKS_REQUIRED: 'remarks is required',
    STUDENT_NOT_APPLIED: "Student don't have any application on this sponsorship",
    APP_STAGE_PARAM_REQUIRED: "applicationStage is required",
    APP_STAGE_PARAM_INVALID: "Invalid applicationStage. Allowed values are: POOLING | APPLICATION_LIST | RANKING_SELECTION | FINAS_PROPER",
    APP_STAGE_REQUIRED: "appStage is required",
    APP_STATUS_REQUIRED: "appStatus is required",
    APP_STAGE_INVALID: "Invalid appStage. Allowed values are: POOLING | APPLICATION_LIST | RANKING_SELECTION | FINAS_PROPER",
    APP_STATUS_INVALID: "Invalid appStatus",
    INVALID_STATUS_FOR_STAGE: "Invalid appStatus for",
    INTERVIEW_STATUS_INVALID: "Invalid interview status",
    EXAM_STATUS_INVALID: "Invalid exam status",
    FORBIDDEN_INTERVIEW_EXAM_CHANGES: "You can only change interview/exam status in application list stage",
    ANN_TITLE_INVALID: "Title must be a string",
    ANN_TITLE_REQUIRED: "Title is required",
    ANN_CONTENT_INVALID: "Content must be a string",
    ANN_CONTENT_REQUIRED: "Content is required",
    ANN_CAPTION_INVALID: "Caption must be a string",
    ANN_CAPTION_REQUIRED: "Caption is required",
    ANN_MUN_EMPTY: "targetMunicipalitys must be a non-empty array",
    ANN_MUN_INVALID_ITEMS: "Each targetMunicipality must be a number",
    ANN_SPON_INVALID_ID: "sponsorshipId must be a valid UUID",
    ANN_CITYMUN_ID_NOT_FOUND: 'municipality ID not found in the system',
    ANN_MUN_INVALID_FORMAT: 'municipality ID array must be string of array',
    ANN_ID_REQUIRED: 'Announcement ID is required',
    ANN_NOT_FOUND: 'Announcement not found or your not the owner',
    GWA_INVALID: 'GWA is Invalid',
    GWA_OUT_OF_BOUNDS: 'GWA is out of bounds',
    BATCH_NO_REQUIRED: "Batch No Required",
    BATCH_NO_NOT_EXIST: "Sponsorship don't have this batch no",
    SCHEDULE_TYPE_REQUIRED: "scheduleType is required",
    SCHEDULE_TYPE_INVALID: "scheduleType must be either TEST or INTERVIEW",
    LOCATION_REQUIRED: "location is required",
    SCHEDULE_QUOTA_REQUIRED: "scheduleQuota is required",
    SCHEDULE_QUOTA_INVALID: "scheduleQuota must be a number greater than or equal to 1",
    START_DATE_REQUIRED: "startDate is required",
    START_DATE_INVALID: "startDate must be a valid datetime",
    END_DATE_REQUIRED: "endDate is required",
    END_DATE_INVALID: "endDate must be a valid datetime",
    END_DATE_INVALID_FORMAT: "Invalid date format",
    END_DATE_BEFORE_START_DATE: "endDate must be greater than startDate",
    SCHED_ID_REQUIRED: "scheduleId is required",
    SCHED_NOT_FOUND: "Schedule doesn't exist",
    SCHEDULE_DELETED: "Schedule succesfully deleted",
    CRIT_CAT_INVALID_ID: "Criterion Category Invalid Id",
    CRIT_CAT_NOT_FOUND: "Criterion Category Not Found",
    CRITERIA_ARRAY_EMPTY: "Criteria must be a non-empty array",
    CRITERIA_NAME_INVALID: 'Each criteria item must have a valid name',
    CRITERIA_LABEL_INVALID: 'Each criteria item must have a valid label',
    CRITERIA_DATASOURCE_INVALID: 'Each criteria item must have a valid dataSource (COLUMN, CUSTOM_INPUT, COMPUTED)',
    CRITERIA_FORMULATYPE_INVALID: 'Each criteria item must have a valid formulaType',
    CRITERIA_PREFERENCE_INVALID: 'Each criteria item must have a valid preference (MIN or MAX)',
    CRITERIA_REQUIREDCOLUMN_INVALID: 'COLUMN and COMPUTED data source criteria must have at least one requiredColumn',
    CRITERIA_REQUIREDCOLUMN_TABLE_INVALID: 'Each requiredColumn for COLUMN or COMPUTED data sources must include a valid table name from the database.',
    CRITERIA_REQUIREDCOLUMN_COLUMN_INVALID: 'Each requiredColumn for COLUMN or COMPUTED data sources must include a valid column that exists within the specified table.',
    CRITERIA_ARRAY_INVALID: 'Criteria must be an array',
    PAIRWISE_ARRAY_EMPTY: 'Pairwise Array must not be empty',
    PAIRWISE_CRITERIA_A_INVALID: 'Please review Criteria A if its valid',
    PAIRWISE_CRITERIA_B_INVALID: 'Please review Criteria B if its valid',
    PAIRWISE_VALUE_INVALID: 'Pairwise comparison value between A and b must be an integer from 1 to 9',
    CRITERION_DUPLICATE: 'Duplicate criterion names are not allowed in the criteria array.',
    CUSTOM_INPUT_ARRAY_INVALID: 'Payload must be an array',
    CUSTOM_INPUT_SPON_ID_INVALID: 'sponsorshipId must be a valid UUID',
    CUSTOM_INPUT_STUD_ID_INVALID: 'studentId must be a valid UUID',
    CUSTOM_INPUT_SPON_CRIT_ID_INVALID: 'sponsorshipCriterionId must be a valid UUID',
    CUSTOM_INPUT_VALUE_INVALID: 'value must be a number',
    CUSTOM_INPUT_VALUE_EMPTY: 'value is required',
    CUSTOM_INPUT_SPON_CRIT_ID_NOT_FOUND: 'sponsorship criterion id not found',
    SLOT_FULL: "No slots available for this sponsorship.",
    LIMIT_REACHED: "The number of accepted applicants has already reached its limit.",
    APPLICATION_NOT_FOUND: "Application not found.",
    CANNOT_CANCEL_APPLICATION: "Application can only be cancelled while in the pooling stage.",
};
